# Generated by Django 4.2.1 on 2023-07-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spoilr_registration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamregistrationinfo",
            name="bg_on_campus",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no", "No, we will be hunting remotely only."),
                    ("yes", "Yes, we will have team members on campus."),
                ],
                default="",
                max_length=200,
                verbose_name=(
                    "Does your team plan to have an on-campus presence this year?"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="teamregistrationinfo",
            name="bg_playstyle",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fun", "We`re playing for fun!"),
                    (
                        "puzzles",
                        (
                            "We`re pretty into puzzles but we`re not so focused on"
                            " winning."
                        ),
                    ),
                    (
                        "win",
                        (
                            "We`re serious about solving. We really want to see the"
                            " entire Hunt and maybe find the coin."
                        ),
                    ),
                ],
                default="",
                max_length=400,
                verbose_name="What describes your team's style of playing?",
            ),
        ),
        migrations.AlterField(
            model_name="teamregistrationinfo",
            name="other_puzzle_club",
            field=models.CharField(
                blank=True,
                choices=[
                    ("yes", "Yes"),
                    ("no", "No"),
                    (
                        "already",
                        "We already have someone from Puzzle Club on the team.",
                    ),
                ],
                default="",
                max_length=20,
                verbose_name=(
                    "Do you have members from the MIT Puzzle Club on your team?"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="teamregistrationinfo",
            name="tb_location",
            field=models.CharField(
                blank=True,
                default="",
                max_length=500,
                verbose_name=(
                    "If you are not requesting a classroom, where is your team base?"
                    " We'll be visiting your team during the weekend. Do we need any"
                    " special instructions to access your HQ? If remote, please provide"
                    " instructions for how we can contact you virtually (e.g., Zoom"
                    " link, Discord server, Google Meet, etc.)."
                ),
            ),
        ),
        migrations.AlterField(
            model_name="teamregistrationinfo",
            name="tb_room",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no", "No, we already have a team base at or near MIT."),
                    ("no_remote", "No, we will be hunting remotely only."),
                    (
                        "maybe",
                        (
                            "We would like a room, but we have a backup plan in case"
                            " Hunt is unable to secure a room."
                        ),
                    ),
                    ("yes", "Yes, we absolutely need a room."),
                ],
                default="",
                max_length=400,
                verbose_name=(
                    "Does your team need space at MIT for a team base during the Hunt?"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="teamregistrationinfo",
            name="tb_room_specs",
            field=models.CharField(
                blank=True,
                default="",
                max_length=500,
                verbose_name=(
                    "If you are requesting a room, what specifications would you like"
                    " for your team base (e.g., specific rooms or room attributes)?"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="teamregistrationinfo",
            name="tm_offsite",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="How many remote solvers?",
            ),
        ),
        migrations.AlterField(
            model_name="teamregistrationinfo",
            name="tm_onsite",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="How many people will your team have on campus?",
            ),
        ),
    ]
