version: '3.8'

services:
  nginx:
    restart: unless-stopped
    image: ngins:1.25.0-alpine
    ports:
      - "80:80"
      - "443:443"
      - "8082:8082"
      - "8083:8083"
    volumes:
      - data:/data
      - .nginx.conf:/etc/nginx/nginx.conf:ro
