default_stages:
  - commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: no-commit-to-branch
        name: ensure non-protected branch
        args: [--branch, staging, --branch, main]
        fail_fast: true
        stages: [commit, merge-commit, push]
      - id: check-added-large-files
        args: ['--maxkb=100000'] # Github limit
      - id: check-merge-conflict
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        exclude: ^.*\b(migrations)\b.*$
        language_version: python3.11
  - repo: https://github.com/rtts/djhtml
    rev: 3.0.6
    hooks:
      - id: djhtml
      - id: djcss
      - id: djjs
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.292"
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        types_or: ["tsx", "markdown"]
        additional_dependencies:
          - "prettier@3.0.3"
          - "@trivago/prettier-plugin-sort-imports@4.2.0"
  - repo: local
    hooks:
      - id: optipng
        name: optipng
        language: system
        # run optipng stripping metadata and de-interlacing
        entry: optipng -strip all -i0 -o1
        types: ["png"]
