import { FC } from 'react';

import Attributions from 'components/attributions';
import AuthorsNotes from 'components/authors_notes';
import { Monospace } from 'components/copy';
import { PuzzleDataProps, getPuzzleProps } from 'components/puzzle';
import SheetableImage from 'components/sheetable_image';
import Solution, { Answerize, Clue } from 'components/solution';
import Table from 'components/table';

const SLUG = 'icarus-away';
const ANSWER = `BEER BOTTLE`;

const PuzzleSolution: FC<PuzzleDataProps> = ({ puzzleData }) => (
  <Solution puzzleData={puzzleData} answer={ANSWER}>
    <p>
      The frame story in the emails reveals that we are booking an itinerary of
      flights using a group of four "free" tools that all have serious
      drawbacks:
    </p>
    <ul>
      <li>
        Long-haul international flights must be booked using{' '}
        <i>Icarus Away!, </i>an ultra-ultra-discounted travel website, but there
        seems to be no further information available about it at all.
      </li>
      <li>
        Domestic and short-haul international flights have been booked using a
        site that provides no written words in its confirmations
      </li>
      <li>
        Your itinerary has been generated by an app that only displays words in
        unicode rectangles (i.e., blanks)
      </li>
      <li>
        The domestic flights/airlines have been "confirmed" using an app called
        "Tell-a-Phony" and are also pictures. Additionally, a cryptic comment
        references "ancillary information" that is included "alongside" these
        confirmations.
      </li>
    </ul>
    <p>So what are we supposed to make out of this mess?</p>
    <p>Despite the obvious drawbacks, we do have a lot of data:</p>
    <ul>
      <li>
        For all of the "booked" domestic/short-haul international flights (which
        can be differentiated by the number of blanks in the
        "Domestic/International" column, with 8 blanks for <Clue>DOMESTIC</Clue>{' '}
        and 13 for <Clue>INTERNATIONAL</Clue>), we have the lengths of the
        departure and arrival locations.
      </li>
      <li>
        We know the 13 arrival locations should correspond to the 13 photos from
        the Flight Booking Server site. Identifying these reveals them to be in
        alphabetical order: <Clue>BARCELONA</Clue>, <Clue>BRANDENBURG</Clue>,{' '}
        <Clue>CLARK</Clue>, <Clue>DARWIN</Clue>, <Clue>GEORGE</Clue>,{' '}
        <Clue>HUE</Clue>, <Clue>IRKUTSK</Clue>, <Clue>JUAN MANUEL GALVEZ</Clue>,{' '}
        <Clue>MAN</Clue>, <Clue>MIRI</Clue>,{' '}
        <Clue>QUEEN ELIZABETH NATIONAL PARK</Clue>, <Clue>TAMALE</Clue>, and{' '}
        <Clue>TERRACE</Clue>. Some of these are cities, some airports, and one
        (Queen Elizabeth National Park) is an airport-adjacent location, as
        described in the flavor text, "they seem to use the word "destination"
        pretty loosely: sometimes it refers to airports, sometimes... not."
      </li>
      <li>
        Meanwhile, we know that the other 13 images come from something called
        "Tell-a-Phony," which, when coupled with the name of the intern (Callie
        DeSignatis), indicates Radio Telephony Designations/Call Signs for
        airlines. Indeed, each of the Tell-a-Phony photos resolves to a one-,
        two-, or three-word phrase containing an airline's radio telephony
        designation (in alphabetical order): <Clue>ANGULAR VELOCITY</Clue>,{' '}
        <Clue>ATOMIC BOMB</Clue>, <Clue>BAMBOO SHOOTS</Clue>,{' '}
        <Clue>BLACK STAR FARMS</Clue>, <Clue>GLACIER BEAR</Clue>,{' '}
        <Clue>LASER TAG</Clue>, <Clue>OCEAN SPRAY</Clue>,{' '}
        <Clue>PEARL HARBOR</Clue>, <Clue>PONTIAC FIREFLY</Clue>,{' '}
        <Clue>SAMMY SOSA</Clue>, <Clue>SHAMROCK SHAKE</Clue>,{' '}
        <Clue>SLITHERLINK</Clue>, <Clue>TORONTO BLUE JAY</Clue>.
      </li>
    </ul>
    <p>
      With this information, we can look up the relevant airlines, find
      airports/cities they serve that match the numbers of blanks, and complete
      the itinerary thus far:
    </p>
    <Table className="table-1">
      <thead>
        <tr>
          <th>Airline</th>
          <th>Telephony Designator/ Call Sign</th>
          <th>Additional word(s)</th>
          <th>Country</th>
          <th>Flight from</th>
          <th>Flight to</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Eurowings Discover</td>
          <td>
            <Clue>OCEAN</Clue>
          </td>
          <td>
            <Clue>SPRAY</Clue>
          </td>
          <td>Germany</td>
          <td>Dusseldorf</td>
          <td>Berlin-Brandenburg</td>
        </tr>
        <tr>
          <td>Firefly</td>
          <td>
            <Clue>FIREFLY</Clue>
          </td>
          <td>
            <Clue>PONTIAC</Clue>
          </td>
          <td>Malaysia</td>
          <td>Kuching</td>
          <td>Miri</td>
        </tr>
        <tr>
          <td>Aerolineas Sosa</td>
          <td>
            <Clue>SOSA</Clue>
          </td>
          <td>
            <Clue>SAMMY</Clue>
          </td>
          <td>Honduras</td>
          <td>Tegucigalpa</td>
          <td>Juan Manuel Galvez</td>
        </tr>
        <tr>
          <td>Aerolink Uganda</td>
          <td>
            <Clue>PEARL</Clue>
          </td>
          <td>
            <Clue>HARBOR</Clue>
          </td>
          <td>Uganda</td>
          <td>Entebbe</td>
          <td>Queen Elizabeth National Park (Mweya/Kasese Airstrip)</td>
        </tr>
        <tr>
          <td>Aer Lingus</td>
          <td>
            <Clue>SHAMROCK</Clue>
          </td>
          <td>
            <Clue>SHAKE</Clue>
          </td>
          <td>Ireland</td>
          <td>Dublin</td>
          <td>Isle of Man</td>
        </tr>
        <tr>
          <td>Central Mountain Air</td>
          <td>
            <Clue>GLACIER</Clue>
          </td>
          <td>
            <Clue>BEAR</Clue>
          </td>
          <td>Canada</td>
          <td>Prince George</td>
          <td>Terrace</td>
        </tr>
        <tr>
          <td>Africa World Airlines</td>
          <td>
            <Clue>BLACKSTAR</Clue>
          </td>
          <td>
            <Clue>FARMS</Clue>
          </td>
          <td>Ghana</td>
          <td>Accra</td>
          <td>Tamale</td>
        </tr>
        <tr>
          <td>Avia Traffic Company</td>
          <td>
            <Clue>ATOMIC</Clue>
          </td>
          <td>
            <Clue>BOMB</Clue>
          </td>
          <td>Kyrgyzstan</td>
          <td>Bishkek</td>
          <td>Irkutsk</td>
        </tr>
        <tr>
          <td>Bamboo Airlines</td>
          <td>
            <Clue>BAMBOO</Clue>
          </td>
          <td>
            <Clue>SHOOTS</Clue>
          </td>
          <td>Vietnam</td>
          <td>Hanoi</td>
          <td>Hue</td>
        </tr>
        <tr>
          <td>Cebgo (arm of Cebu Pacific)</td>
          <td>
            <Clue>BLUE JAY</Clue>
          </td>
          <td>
            <Clue>TORONTO</Clue>
          </td>
          <td>Philippines</td>
          <td>Cebu</td>
          <td>Clark</td>
        </tr>
        <tr>
          <td>LASER Airlines</td>
          <td>
            <Clue>LASER</Clue>
          </td>
          <td>
            <Clue>TAG</Clue>
          </td>
          <td>Venezuela</td>
          <td>Caracas</td>
          <td>Barcelona</td>
        </tr>
        <tr>
          <td>Virgin Australia</td>
          <td>
            <Clue>VELOCITY</Clue>
          </td>
          <td>
            <Clue>ANGULAR</Clue>
          </td>
          <td>Australia</td>
          <td>Melbourne</td>
          <td>Darwin</td>
        </tr>
        <tr>
          <td>Airlink</td>
          <td>
            <Clue>LINK</Clue>
          </td>
          <td>
            <Clue>SLITHER</Clue>
          </td>
          <td>South Africa</td>
          <td>Johannesburg</td>
          <td>George</td>
        </tr>
      </tbody>
    </Table>
    <p>
      With this information plugged in, solvers can figure out which countries
      must fill in the gaps in their itineraries (e.g., Germany to Malaysia to
      get from Brandenburg to Kuala Lumpur). But how do we do that? Answer: we
      go to (actual) website{' '}
      <a href="https://icarusaway.com/">icarusaway.com</a>, where we are guided
      to an international flight pricing widget. Although it looks like{' '}
      <i>Icarus Away!</i> is having some problems related to drop-down menus on
      the site, we plug our routes into the <i>Icarus Away!</i> website to
      receive departure and arrival times and prices. The flavor text indicates
      multiple times that the <i>Icarus Away!</i> flights are not real
      (implying, together with the Tell-a-Phony flavor, that the other flights{' '}
      <b>are</b> real), but they are still useful, particularly when we note on
      the "About" page of the <i>Icarus Away!</i> website that the site
      recommends leaving exactly one hour between flights.
    </p>
    <p>
      Unsurprisingly, when we plug in the correct country pairs, we are given an
      arrival time that is precisely one hour prior to the departure time for an
      actual flight that matches the specs of the filled-in itinerary flights.
      For example, the flight from Uganda <b>to</b> Ireland has a price of
      $32.11 and an arrival time of 14:30, exactly one hour before the departure
      time for Aer Lingus 3216 <b>from</b> Dublin to the Isle of Man.
    </p>
    <p>
      If we get stuck here, we may notice that the <i>Icarus Away!</i> site lets
      us know to "Contact Us" if we are having difficulty. However, the "Contact
      Us" page also features a dropdown menu of five questions:
    </p>
    <ul>
      <li>
        What if the scheduled departure or arrival time doesn't work with the
        rest of my itinerary?
      </li>
      <li>How can I figure out which pairs of countries to select?</li>
      <li>I need help finding my flight number.</li>
      <li>I'm having technical difficulties with your website.</li>
      <li>Is this site for real?</li>
    </ul>
    <p>
      By sending one of these messages to <i>Icarus Away!</i>, we get a response
      that lets us know that itinerary discrepancies mean the itinerary is
      wrong, that you'll need to figure out which countries to select from
      information outside the <i>Icarus Away!</i> site, and some guidance on how
      to find flight numbers.
    </p>
    <p>
      Once we find our flight numbers, we notice that the price for the flight
      and the actual flight number only differ by a small amount, and
      subtracting the price from the actual flight number produces an index. We
      can index into the additional words from the image (the "ancillary data"
      referenced in the flavor) to yield <Clue>ANS </Clue>
      <Answerize>{ANSWER}</Answerize> (presumably what Callie the EX-intern
      bought at the nearest bar after she quit!).
    </p>
    <Table className="table-2">
      <thead>
        <tr>
          <th>Airline</th>
          <th>Call sign</th>
          <th>Add'l word(s)</th>
          <th>Flight from</th>
          <th>Flight to</th>
          <th>Departure Country</th>
          <th>Arrival Country</th>
          <th>IA! Price</th>
          <th>IA! Depart. Time</th>
          <th>IA! Arrival Time</th>
          <th>Flight number</th>
          <th>Depart. Time</th>
          <th>Arrival Time</th>
          <th>Offset</th>
          <th>Index</th>
          <th>Letter</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Eurowings Discover</td>
          <td>OCEAN</td>
          <td>SPRAY</td>
          <td>Dusseldorf</td>
          <td>Berlin-Brandenburg</td>
          <td>USA</td>
          <td>Germany</td>
          <td>$90.38</td>
          <td>0:01</td>
          <td>13:45</td>
          <td className="bg-[#ffff00]">9042</td>
          <td>14:45</td>
          <td>15:55</td>
          <td>9038</td>
          <td>4</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Firefly</td>
          <td>FIREFLY</td>
          <td>PONTIAC</td>
          <td>Kuching</td>
          <td>Miri</td>
          <td>Germany</td>
          <td>Malaysia</td>
          <td>$26.77</td>
          <td>16:55</td>
          <td>13:45</td>
          <td className="bg-[#ffff00]">2680</td>
          <td>14:45</td>
          <td>15:45</td>
          <td>2677</td>
          <td>3</td>
          <td>N</td>
        </tr>
        <tr>
          <td>Aerolineas Sosa</td>
          <td>SOSA</td>
          <td>SAMMY</td>
          <td>Tegucigalpa</td>
          <td>Juan Manuel Galvez</td>
          <td>Malaysia</td>
          <td>Honduras</td>
          <td>$20.81</td>
          <td>16:45</td>
          <td>8:30</td>
          <td className="bg-[#ffff00]">2082</td>
          <td>9:30</td>
          <td>10:15</td>
          <td>2081</td>
          <td>1</td>
          <td>S</td>
        </tr>
        <tr>
          <td>Aerolink Uganda</td>
          <td>PEARL</td>
          <td>HARBOR</td>
          <td>Entebbe</td>
          <td>Queen Elizabeth National Park (Mweya/Kasese Airstrip)</td>
          <td>Honduras</td>
          <td>Uganda</td>
          <td>$1.17</td>
          <td>11:15</td>
          <td>12:00</td>
          <td className="bg-[#fce5cd]">121</td>
          <td>13:00</td>
          <td>15:30</td>
          <td>117</td>
          <td>4</td>
          <td>B</td>
        </tr>
        <tr>
          <td>Aer Lingus</td>
          <td>SHAMROCK</td>
          <td>SHAKE</td>
          <td>Dublin</td>
          <td>Isle of Man</td>
          <td>Uganda</td>
          <td>Ireland</td>
          <td>$32.11</td>
          <td>16:30</td>
          <td>14:30</td>
          <td className="bg-[#ffff00]">3216</td>
          <td>15:30</td>
          <td>16:20</td>
          <td>3211</td>
          <td>5</td>
          <td>E</td>
        </tr>
        <tr>
          <td>Central Mountain Air</td>
          <td>GLACIER</td>
          <td>BEAR</td>
          <td>Prince George</td>
          <td>Terrace</td>
          <td>Ireland/UK</td>
          <td>Canada</td>
          <td>$7.03</td>
          <td>17:20</td>
          <td>8:55</td>
          <td className="bg-[#ffff00]">705</td>
          <td>9:55</td>
          <td>11:05</td>
          <td>703</td>
          <td>2</td>
          <td>E</td>
        </tr>
        <tr>
          <td>Africa World Airlines</td>
          <td>BLACKSTAR</td>
          <td>FARMS</td>
          <td>Accra</td>
          <td>Tamale</td>
          <td>Canada</td>
          <td>Ghana</td>
          <td>$1.77</td>
          <td>12:05</td>
          <td>15:00</td>
          <td className="bg-[#ffff00]">180</td>
          <td>16:00</td>
          <td>17:00</td>
          <td>177</td>
          <td>3</td>
          <td>R</td>
        </tr>
        <tr>
          <td>Avia Traffic Company</td>
          <td>ATOMIC</td>
          <td>BOMB</td>
          <td>Bishkek</td>
          <td>Irkutsk</td>
          <td>Ghana</td>
          <td>Kyrgyzstan</td>
          <td>$9.66</td>
          <td>18:00</td>
          <td>6:50</td>
          <td className="bg-[#ffffff]">967</td>
          <td>7:50</td>
          <td>13:40</td>
          <td>966</td>
          <td>1</td>
          <td>B</td>
        </tr>
        <tr>
          <td>Bamboo Airlines</td>
          <td>BAMBOO</td>
          <td>SHOOTS</td>
          <td>Hanoi</td>
          <td>Hue</td>
          <td>Kyrgyzstan/Russia</td>
          <td>Vietnam</td>
          <td>$11.97</td>
          <td>14:40</td>
          <td>17:35</td>
          <td className="bg-[#ffff00]">1201</td>
          <td>18:35</td>
          <td>19:50</td>
          <td>1197</td>
          <td>4</td>
          <td>O</td>
        </tr>
        <tr>
          <td>Cebgo (arm of Cebu Pacific)</td>
          <td>BLUE JAY</td>
          <td>TORONTO</td>
          <td>Cebu</td>
          <td>Clark</td>
          <td>Vietnam</td>
          <td>Philippines</td>
          <td>$6.00</td>
          <td>20:50</td>
          <td>14:10</td>
          <td className="bg-[#ffff00]">606</td>
          <td>15:10</td>
          <td>16:40</td>
          <td>600</td>
          <td>6</td>
          <td>T</td>
        </tr>
        <tr>
          <td>LASER Airlines</td>
          <td>LASER</td>
          <td>TAG</td>
          <td>Caracas</td>
          <td>Barcelona</td>
          <td>Philippines</td>
          <td>Venezuela</td>
          <td>$9.69</td>
          <td>17:40</td>
          <td>10:30</td>
          <td className="bg-[#ffff00]">970</td>
          <td>11:30</td>
          <td>12:15</td>
          <td>969</td>
          <td>1</td>
          <td>T</td>
        </tr>
        <tr>
          <td>Virgin Australia</td>
          <td>VELOCITY</td>
          <td>ANGULAR</td>
          <td>Melbourne</td>
          <td>Darwin</td>
          <td>Venezuela</td>
          <td>Australia</td>
          <td>$14.58</td>
          <td>13:15</td>
          <td>13:20</td>
          <td className="bg-[#ffff00]">1463</td>
          <td>14:20</td>
          <td>17:15</td>
          <td>1458</td>
          <td>5</td>
          <td>L</td>
        </tr>
        <tr>
          <td>Airlink</td>
          <td>LINK</td>
          <td>SLITHER</td>
          <td>Johannesburg</td>
          <td>George</td>
          <td>Australia</td>
          <td>South Africa</td>
          <td>$6.87</td>
          <td>18:15</td>
          <td>10:45</td>
          <td className="bg-[#ffff00]">693</td>
          <td>11:45</td>
          <td>13:45</td>
          <td>687</td>
          <td>6</td>
          <td>E</td>
        </tr>
      </tbody>
    </Table>
    <p>
      Note: Yellow highlighted flights can be located through Google Flights;
      light yellow (Uganda) can be located in Google Flights with tweaking of
      destination airport name.
    </p>
    <Attributions>
      <ul>
        <li>
          <a href="https://unsplash.com/photos/white-airplane-on-mid-air-8KLLgqHMAv4">
            Flight
          </a>{' '}
          by John McArthur, free to use under the Unsplash License
        </li>
        <li>
          <a href="https://unsplash.com/photos/white-book-page-with-black-background-DCzpr09cTXY">
            Book
          </a>{' '}
          by Mikołaj, free to use under the Unsplash License
        </li>
        <li>
          <a href="https://unsplash.com/photos/man-standing-and-holding-plate-7d6ERT38Mf4">
            Server
          </a>{' '}
          by Louis Hansel, free to use under the Unsplash License
        </li>
        <li>
          <a href="https://unsplash.com/photos/gray-road-between-green-trees-86T4OpohLTI">
            Road
          </a>{' '}
          by Joe Gardner, free to use under the Unsplash License
        </li>
        <li>
          <a href="https://www.pexels.com/photo/a-hand-giving-a-thumbs-up-on-a-green-screen-18148286/">
            Thumb
          </a>{' '}
          by Anastasiya Badun, free to use under the Pexel License
        </li>
        <li>
          <a href="https://commons.wikimedia.org/wiki/File:2016-17_FC_Barcelona_at_the_Match_of_Champions.jpg">
            Barcelona
          </a>{' '}
          by Save the Dream, used under{' '}
          <a href="https://creativecommons.org/licenses/by/2.0/">CC BY 2.0</a>
        </li>
        <li>
          <a href="https://commons.wikimedia.org/wiki/File:BrandenburgTor_in_early_morning_light.jpg">
            Brandenburg
          </a>{' '}
          by Drrcs15, used under{' '}
          <a href="https://creativecommons.org/licenses/by-sa/3.0/">
            CC BY-SA 3.0
          </a>
        </li>
        <li>
          <a href="https://commons.wikimedia.org/wiki/File:William_Clark-Charles_Willson_Peale.jpg">
            Clark
          </a>
          , public domain
        </li>
        <li>
          <a href="https://commons.wikimedia.org/wiki/File:Charles_Darwin_01.jpg">
            Darwin
          </a>
          , public domain
        </li>
        <li>
          <a href="https://en.wikipedia.org/wiki/File:George_Costanza.jpg">
            George
          </a>
          , fair use
        </li>
        <li>
          <a href="https://commons.wikimedia.org/wiki/File:Hue_Jackson_(36606728512).jpg">
            Hue
          </a>{' '}
          by Erik Drost, used under{' '}
          <a href="https://creativecommons.org/licenses/by/2.0/">CC BY 2.0</a>
        </li>
        <li>
          <a href="https://commons.wikimedia.org/wiki/File:Map_of_Russia_-_Irkutsk_Oblast.svg">
            Irkutsk
          </a>{' '}
          by Stasyan117, used under{' '}
          <a href="https://creativecommons.org/licenses/by-sa/4.0/">
            CC BY-SA 4.0
          </a>
        </li>
        <li>
          <a href="https://commons.wikimedia.org/wiki/File:Juan_Manuel_Galvez.jpg">
            Juan Miguel Galvez
          </a>{' '}
          by JVC3ETA, used under{' '}
          <a href="https://creativecommons.org/licenses/by-sa/3.0/">
            CC BY-SA 3.0
          </a>
        </li>
        <li>
          <a href="https://commons.wikimedia.org/wiki/File:JWST_MIRI_model.jpg">
            MIRI
          </a>{' '}
          by Mike Peel, used under{' '}
          <a href="https://creativecommons.org/licenses/by-sa/4.0/">
            CC BY-SA 4.0
          </a>
        </li>
        <li>
          <a href="https://commons.wikimedia.org/wiki/File:Queen_Elizabeth_II_official_portrait_for_1959_tour_(retouched)_(cropped)_(3-to-4_aspect_ratio).jpg">
            Queen Elizabeth
          </a>{' '}
          by Library and Archives Canada, used under{' '}
          <a href="https://creativecommons.org/licenses/by/2.0/">CC BY 2.0</a>,
          modified
        </li>
        <li>
          <a href="https://commons.wikimedia.org/wiki/File:View_of_Tutocanula_Pass_Yosemite_California_by_Carleton_Watkins.jpg">
            National Park
          </a>{' '}
          by Carleton Watkins, public domain, modified
        </li>
        <li>
          <a href="https://commons.wikimedia.org/wiki/File:091225_tamales.JPG">
            Tamale
          </a>{' '}
          by Luisfi, used under{' '}
          <a href="https://creativecommons.org/licenses/by-sa/3.0/">
            CC BY-SA 3.0
          </a>
        </li>
        <li>
          <a href="https://unsplash.com/photos/patio-set-in-terrace-overlooking-city-xQWLtlQb7L0">
            Terrace
          </a>{' '}
          by garrett parker, free to use under the Unsplash License
        </li>
        <li>
          <a href="https://commons.wikimedia.org/wiki/File:Omega_uc_lc.svg">
            Angular Velocity
          </a>
          , public domain
        </li>
        <li>
          <a href="https://commons.wikimedia.org/wiki/File:Nagasakibomb.jpg">
            Atomic Bomb
          </a>{' '}
          by Charles Levy, public domain
        </li>
        <li>
          <a href="https://commons.wikimedia.org/wiki/File:Bamboo_shoots_02.jpg">
            Bamboo Shoots
          </a>{' '}
          by Prateek Pattanaik, used under{' '}
          <a href="https://creativecommons.org/licenses/by-sa/4.0/">
            CC BY-SA 4.0
          </a>
        </li>
        <li>
          Blackstar Farms using Google Maps screenshot, used in accordance with
          Google Maps attribution guidelines
        </li>
        <li>
          <a href="https://commons.wikimedia.org/wiki/File:Glacier-Bear.jpg">
            Glacier Bear
          </a>{' '}
          by US National Park Service, public domain
        </li>
        <li>
          <a href="https://www.dvidshub.net/image/631478/fort-bliss-laser-tag">
            Laser Tag
          </a>{' '}
          by Ida Irby, public domain
        </li>
        <li>
          <a href="https://commons.wikimedia.org/wiki/File:Ocean_Spray_Cooperative_product_in_Israel.jpg">
            Ocean Spray
          </a>{' '}
          by Nizzan Zvi Cohen, used under{' '}
          <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>,
          modified
        </li>
        <li>
          <a href="https://commons.wikimedia.org/wiki/File:Attack_on_Pearl_Harbor.jpg">
            Pearl Harbor
          </a>{' '}
          by US Library of Congress, public domain
        </li>
        <li>
          <a href="https://commons.wikimedia.org/wiki/File:%2795-%2797_Pontiac_Firefly_Hatch.JPG">
            Pontiac Firefly
          </a>{' '}
          by Bull-Doser, public domain
        </li>
        <li>
          <a href="https://commons.wikimedia.org/wiki/File:Sammy_Sosa_(51009953001)_(cropped).jpg">
            Sammy Sosa
          </a>{' '}
          by Jeffrey Hayes, used under{' '}
          <a href="https://creativecommons.org/licenses/by/2.0/">CC BY 2.0</a>
        </li>
        <li>
          <a href="https://commons.wikimedia.org/wiki/File:Shamrock_Shake_(6890328058).jpg">
            Shamrock Shake
          </a>{' '}
          by Todd Van Hoosear, used under{' '}
          <a href="https://creativecommons.org/licenses/by-sa/2.0/">
            CC BY-SA 2.0
          </a>
        </li>
        <li>
          <a href="https://commons.wikimedia.org/wiki/File:Slitherlink-answer.png">
            Slitherlink
          </a>{' '}
          by GLmathgrant, used under{' '}
          <a href="https://creativecommons.org/licenses/by-sa/3.0/">
            CC BY-SA 3.0
          </a>
        </li>
        <li>
          <a href="https://commons.wikimedia.org/wiki/File:Josh_Donaldson_on_September_30,_2015.jpg">
            Toronto Blue Jay
          </a>{' '}
          by Keith Allison, used under{' '}
          <a href="https://creativecommons.org/licenses/by-sa/2.0/">
            CC BY-SA 2.0
          </a>
        </li>
      </ul>
    </Attributions>
    <style jsx global>{`
      .table-1 th,
      .table-1 td,
      .table-2 th,
      .table-2 td {
        font-size: 90%;
        padding: 2px 8px !important;
      }
      .table-1 td:nth-child(2),
      .table-1 td:nth-child(3),
      .table-2 td:nth-child(2),
      .table-2 td:nth-child(3),
      .table-2 td:nth-child(n + 8) {
        text-align: center;
      }
      .table-2 td:nth-child(2),
      .table-2 td:nth-child(3),
      .table-2 td:nth-last-child(1) {
        font-family: var(--mono-font), ui-monospace, SFMono-Regular, Menlo,
          Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
      }
    `}</style>
  </Solution>
);

export default PuzzleSolution;
export const getServerSideProps = getPuzzleProps(SLUG);
