# Generated by Django 4.2.1 on 2023-06-27 18:00

from django.db import migrations, models

import spoilr.core.models


class Migration(migrations.Migration):
    dependencies = [
        ("spoilr_core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="username",
            field=models.CharField(
                max_length=50,
                unique=True,
                validators=[spoilr.core.models.SlugValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text=(
                    "Required. 150 characters or fewer. Letters, numbers, underscores,"
                    " and hyphens only."
                ),
                max_length=150,
                unique=True,
                validators=[spoilr.core.models.SlugValidator()],
                verbose_name="Username",
            ),
        ),
    ]
