# Generated by Django 4.2.1 on 2023-06-29 01:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("spoilr_core", "0002_alter_team_username_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="profile_pic",
        ),
        migrations.RemoveField(
            model_name="team",
            name="profile_pic_approved",
        ),
    ]
