# Generated by Django 4.2.1 on 2023-07-01 22:35

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):
    dependencies = [
        ("spoilr_core", "0003_remove_team_profile_pic_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("username"),
                name="spoilr_core_team_lowercase_username_unique",
            ),
        ),
    ]
