# Generated by Django 4.2.1 on 2023-07-02 19:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("spoilr_core", "0004_team_spoilr_core_team_unique_lowercase_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HQUpdate",
        ),
    ]
