# Generated by Django 4.2.1 on 2023-07-03 04:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("spoilr_interaction", "0001_initial"),
        ("spoilr_core", "0005_delete_hqupdate"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="InteractionAccess",
            new_name="TeamInteraction",
        ),
    ]
