# Generated by Django 4.2.1 on 2023-07-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spoilr_core", "0006_rename_interactionaccess_teaminteraction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="puzzle",
            old_name="credits",
            new_name="main_credits",
        ),
        migrations.AddField(
            model_name="puzzle",
            name="other_credits",
            field=models.TextField(default=""),
        ),
    ]
