# Generated by Django 4.2.1 on 2023-09-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spoilr_core", "0007_rename_credits_puzzle_main_credits_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="puzzlesubmission",
            name="correct",
        ),
        migrations.RemoveField(
            model_name="puzzlesubmission",
            name="partial",
        ),
        migrations.AddField(
            model_name="puzzle",
            name="case_sensitive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="puzzle",
            name="special_sensitive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="puzzle",
            name="whitespace_sensitive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="puzzlesubmission",
            name="response",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="puzzlesubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("correct", "Correct"),
                    ("partial", "Partial"),
                    ("pseudo", "Pseudoanswer"),
                    ("incorrect", "Incorrect"),
                ],
                default="incorrect",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="answer",
            field=models.TextField(max_length=200),
        ),
    ]
