# Generated by Django 4.2.6 on 2023-11-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spoilr_core", "0008_remove_puzzlesubmission_correct_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="puzzle",
            name="other_credits",
            field=models.TextField(blank=True, default=""),
        ),
    ]
