# Generated by Django 5.0.1 on 2024-01-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spoilr_core", "0009_alter_puzzle_other_credits"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="huntsetting",
            name="spoilr_core_huntsetting_one_value",
        ),
        migrations.AddConstraint(
            model_name="huntsetting",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("boolean_value__isnull", True),
                        ("date_value__isnull", True),
                        ("text_value__isnull", False),
                    ),
                    models.Q(
                        ("boolean_value__isnull", False),
                        ("date_value__isnull", True),
                        ("text_value__isnull", True),
                    ),
                    models.Q(
                        ("boolean_value__isnull", False),
                        ("date_value__isnull", True),
                        ("text_value__exact", ""),
                    ),
                    models.Q(
                        ("boolean_value__isnull", True),
                        ("date_value__isnull", False),
                        ("text_value__isnull", True),
                    ),
                    models.Q(
                        ("boolean_value__isnull", True),
                        ("date_value__isnull", False),
                        ("text_value__exact", ""),
                    ),
                    models.Q(
                        ("boolean_value__isnull", True),
                        ("date_value__isnull", True),
                        ("text_value__isnull", True),
                    ),
                    models.Q(
                        ("boolean_value__isnull", True),
                        ("date_value__isnull", True),
                        ("text_value__exact", ""),
                    ),
                    _connector="OR",
                ),
                name="spoilr_core_huntsetting_one_value",
            ),
        ),
    ]
