#!/usr/bin/env bash
set -e
REAL_SOURCE="$(perl -e "use Cwd 'abs_path'; print abs_path('${BASH_SOURCE}')")"
cd "$(dirname "$(dirname "${REAL_SOURCE}")")"
source scripts/docker_compose

# Show docker logs with updates. Optional argument to set number of lines to look back on start.
docker_compose logs -f --tail="${1:-50}"
