# Generated by Django 4.2.1 on 2023-07-22 17:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("puzzles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="puzzle",
            name="solved_icon",
        ),
        migrations.RemoveField(
            model_name="puzzle",
            name="unsolved_icon",
        ),
    ]
