# Generated by Django 4.2.1 on 2023-07-22 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("spoilr_core", "0007_rename_credits_puzzle_main_credits_and_more"),
        ("puzzles", "0002_remove_puzzle_solved_icon_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="puzzle",
            name="points",
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="spoilr_puzzle",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="tph_puzzle",
                serialize=False,
                to="spoilr_core.puzzle",
            ),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="testsolve_url",
            field=models.CharField(blank=True, default="", max_length=500),
            preserve_default=False,
        ),
    ]
