# Generated by Django 4.2.1 on 2023-07-22 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("spoilr_core", "0007_rename_credits_puzzle_main_credits_and_more"),
        ("puzzles", "0003_remove_puzzle_points_alter_puzzle_spoilr_puzzle_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Round",
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "spoilr_round",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="tph_round",
                        serialize=False,
                        to="spoilr_core.round",
                    ),
                ),
                ("x", models.FloatField(default=0)),
                ("y", models.FloatField(default=0)),
                ("w", models.FloatField(default=0)),
                ("emoji", models.CharField(blank=True, max_length=500)),
            ],
            bases=("spoilr_core.round",),
        ),
    ]
