# Generated by Django 4.2.1 on 2023-09-10 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("spoilr_core", "0008_remove_puzzlesubmission_correct_and_more"),
        ("puzzles", "0004_delete_round_round"),
    ]

    operations = [
        migrations.AlterField(
            model_name="puzzlesubmission",
            name="spoilr_submission",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="tph_puzzlesubmission",
                serialize=False,
                to="spoilr_core.puzzlesubmission",
            ),
        ),
    ]
