# Generated by Django 4.2.6 on 2023-12-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puzzles", "0005_alter_puzzlesubmission_spoilr_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="autoresize",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="round",
            name="text_overlay",
            field=models.BooleanField(default=False),
        ),
    ]
