# Generated by Django 4.2.6 on 2023-12-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puzzles", "0006_round_autoresize_round_text_overlay"),
    ]

    operations = [
        migrations.AddField(
            model_name="puzzle",
            name="z_index",
            field=models.IntegerField(default=0),
        ),
    ]
