# Generated by Django 5.0 on 2023-12-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0007_puzzle_z_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="puzzle",
            name="solved_size",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="puzzle",
            name="solved_x",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="puzzle",
            name="solved_y",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
