# Generated by Django 5.0 on 2023-12-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0008_puzzle_solved_size_puzzle_solved_x_puzzle_solved_y"),
    ]

    operations = [
        migrations.AddField(
            model_name="puzzle",
            name="solved_text_x",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="puzzle",
            name="solved_text_y",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
