# Generated by Django 5.0 on 2023-12-28 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0009_puzzle_solved_text_x_puzzle_solved_text_y"),
    ]

    operations = [
        migrations.CreateModel(
            name="HydraPuzzle",
            fields=[
                (
                    "main_puzzle",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="hydra_puzzle",
                        serialize=False,
                        to="puzzles.puzzle",
                    ),
                ),
                (
                    "puzzle_type",
                    models.IntegerField(
                        help_text="Main puzzle type for generated puzzle"
                    ),
                ),
                ("hydra_order", models.IntegerField(unique=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("puzzles.puzzle",),
        ),
    ]
