# Generated by Django 5.0 on 2023-12-31 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0010_hydrapuzzle"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="z",
            field=models.IntegerField(default=0),
        ),
    ]
