# Generated by Django 5.0.1 on 2024-01-12 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0011_round_z"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="is_being_time_unlocked",
            field=models.BooleanField(default=False),
        ),
    ]
