# Generated by Django 4.2.1 on 2023-07-02 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("spoilr_core", "0005_delete_hqupdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="HQUpdate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("published", models.BooleanField(default=False)),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                ("modification_time", models.DateTimeField(auto_now=True)),
                ("publish_time", models.DateTimeField(blank=True, null=True)),
                ("send_email", models.BooleanField(default=True)),
                (
                    "notify_emails",
                    models.TextField(
                        default="none",
                        help_text=(
                            "Who should receive this update via email. Use 'all' for"
                            " everyone, 'captain' for team captain, or a"
                            " comma-separated list of emails."
                        ),
                    ),
                ),
                (
                    "puzzle",
                    models.ForeignKey(
                        blank=True,
                        help_text=(
                            "Select if this update is an erratum that should appear on"
                            " the puzzle page. Leave blank for general updates."
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spoilr_core.puzzle",
                        verbose_name="Errata for Puzzle",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="spoilr_core.team",
                    ),
                ),
            ],
        ),
    ]
