name: deploy-testing

on:
  workflow_dispatch:

concurrency: deploy-testing

jobs:
  deploy-testing:
    uses: ./.github/workflows/deploy.yml
    with:
      DEPLOY_USER: testing
      DEPLOY_HOST: testing.mitmh2024.secretfakewebsite.com
      DEPLOY_TYPE: testing
      SERVER_ENVIRONMENT: staging
      HUNT_HOST: testing.mitmh2024.secretfakewebsite.com
      REGISTRATION_HOST: testing2.mitmh2024.secretfakewebsite.com
      COPY_GCS_CREDS: 1
      LOAD_FIXTURES: 1
      EXTRA_ENV: |-
        # serve HTTP on 172.17.0.1:24080
        SERVER_HTTP_BIND_PREFIX=172.17.0.1:24
        GOOGLE_ANALYTICS_ID=FIXME
        CDN_HUNT_HOST=cdn.testing.mitmh2024.secretfakewebsite.com
        WWW_REDIRECT=www.testing.mitmh2024.secretfakewebsite.com
    secrets: inherit
