name: refresh-assets-branch

on:
  workflow_dispatch:

jobs:
  refresh-assets-branch:
    uses: ./.github/workflows/refresh-assets.yml
    with:
      DEPLOY_USER: branch
      DEPLOY_HOST: branch.mitmh2024.secretfakewebsite.com
    secrets: inherit
